[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration pour les fonctions Next.js API Routes
[functions]
  included_files = ["package.json"]
  node_bundler = "esbuild"

# Augmenter les limites de temps d'exécution pour les fonctions API
[functions."api/*"]
  timeout = 10

# Désactiver le minify qui peut causer des problèmes
[build.processing]
  skip_processing = false

[build.processing.js]
  bundle = true
  minify = false

# Redirections pour les API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Headers pour CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-store, no-cache"
