[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/_next/static/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# For Next.js apps
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[functions]
  node_bundler = "esbuild"
